title: Hello to New Day!!
date: 2019-12-20
author:Shivani
email: shivi0193.usa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My first time with GitHub Pages

# social links
twitter_username: your-twitter-handle
github_username:  shivani2503

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
